### ISSUE TITLE
Example Todo: Can not run in Iceweasel

### ISSUE THREAD

**Issue by masaoliou** [fastmail/overture#11]
While Opera 12.14 displays example "Todo", Iceweasel 32.0.3 shows nothing and its debug console has these two messages:

SecurityError: The operation is insecure.
TypeError: O.RPCSource is not a constructor

**Comment by neilj** [comment]
It works fine in Firefox (34, the latest version). Not sure why your IceWeasel version wouldn't work, unless you have an extension installed interfering with some of the content perhaps. Are you trying it locally or at http://overturejs.com/examples/Todo/ ?

**Comment by masaoliou** [comment]
I don't remember I ever installed any extension.
Running both http://overturejs.com/examples/Todo and locally yield the same result.

By the way, Iceweasel is running in Debian.

**Comment by masaoliou** [comment]
Running locally with Opera produces the following error and nothing is displayed:

Uncaught exception: ReferenceError: Undefined variable: O
Error thrown at line 42, column 0 in file://localhost/home/examples/Todo/Todo.js:
    App.source = new O.RPCSource({

**Comment by neilj** [comment]
You'll need to build the library (run `make build`; see the readme for environment requirements) first to run it locally.

**Comment by masaoliou** [comment]
Having completed the installation, Opera is now able to display Todo.
Iceweasel still reports errors in its console:
```
SecurityError: The operation is insecure. Overture-raw.js:8398
TypeError: O.RPCSource is not a constructor Todo.js:42
```
The first error points to
```
}( O, window, document, localStorage ) );
```
and the second one points to
```
App.source = new O.RPCSource({
```

**Comment by masaoliou** [comment]
I get this error in console with Iceweasel after logged in fastmail
```
SecurityError: The operation is insecure. www.fastmail.com:33
```
which points to code `<body class="">` while the browser shows `Loading... ` and stops there.

**Comment by neilj** [comment]
No idea really, but it's probably caused by some about:config setting in IceWeasel you've changed (whether on purpose or inadvertently). I'm not going to spend any time worrying about it, but if you can use the debug tools to actually figure out what's going on, I'd be interested to hear what you find.

**Comment by masaoliou** [comment]
Indeed! Tor browser, which stores its settings in an isolated path, does not have such problem.
