### ISSUE TITLE
How to/Who will add more views?

### ISSUE THREAD

**Issue by masaoliou** [fastmail/overture#12]
Does this library expect users to create more views like tabs/pages, date picker, and datetime picker (supporting Gregorian, Islam, and Jalali calendars), tree, etc., or developers will do it?

**Comment by raphonic** [comment]
Overture is similar to angular,ember etc. The users are expected to create (or integrate) the various UI libraries that they may need. There are two routes you could go with
1. Create own views that are based on Overture's views
2.Write wrappers to external libraries like Jquery UI (which would be to call the rendering
code of the individual components after your view is loaded).
