### ISSUE TITLE
RPCSource#handle a public method, function map clarification

### ISSUE THREAD

**Issue by jonathanyc** [fastmail/overture#14]
Thanks for open-sourcing this library! It's very interesting to read over.

While looking at the Todo example, I noticed that there is a call made to App.source.handle in order to register handlers for the TodoList type. I was surprised to not find this method in the documentation. Is this supposed to be a private method? If so, why is it used in the Todo example?

My second question regards the documentation for RPCSource#recordCommitters, etc., which the documentation says map type name strings to functions. I was confused at first as to how then RPCSource was supposed to implement RPC, as this didn't seem to be at all related to the JSON request format described above. On reading the code, though, I think I have come to realize that it's not actually a map of type name strings (I assumed it meant things like "TodoList", etc.) to functions, but rather a map of GUIDs to either strings specifying RPC method names or functions (in some cases). Is this correct? If so, I think that the documentation should make this more clear.

Thanks again for the library!

**Comment by neilj** [comment]
The handle method was added recently and I was lackadaisical in adding docs. I will rectify this soon! This is definitely a public method, and the usage in the Todo app is fairly idiomatic.

Regarding the recordCommitters object etc., this was also changed recently (to support the new handle method) and I missed updating the documentation. Sorry; I will fix this soon too. It now maps from the GUID (as returned by O.guid) of the type constructor to the handling function, as you have already surmised.

**Comment by jonathanyc** [comment]
Cool! Thanks very much, really appreciate your work.
