### ISSUE TITLE
overture + angular/ionic

### ISSUE THREAD

**Issue by smallbitt** [fastmail/overture#19]
Hi, 
is it possible to include overture inside a ionic/angular project?

I tried and I found out that there are scope problems and many errors occurs.

**Comment by neilj** [comment]
I don't know. I don't see why not, but I've never used ionic or angular, so I couldn't really comment. The only conflict I see would be if angular/ionic didn't like the prototype extensions, but there's not many of them.

**Comment by smallbitt** [comment]
Hi Neil, thanks for the answer, isn’t overture an alternative to angular? so I guess that it doesn’t work because they are in same level and they bave theyr own scope. Am I wrong?

> Il giorno 17 feb 2017, alle ore 19:47, Neil Jenkins <notifications@github.com> ha scritto:
> 
> prototype extensions

**Comment by neilj** [comment]
It is an alternative, but that doesn't mean they can't coexist if you really want to. In general, it would probably be better to just pick one though, yes.

**Comment by smallbitt** [comment]
Hi Neil, 
as I try to include overture.js in my ionic project, in the console log I get this error:

I think all begins from here.. and I can’t understand how to solve it.

0     738976   error    TypeError: document.body is null, http://localhost:8100/lib/overture/Overture.js, Line: 7312

**Comment by neilj** [comment]
If `document.body` is `null`, it doesn't look like you have a DOM, at least not fully formed. Try injecting `Overture.js`at the end of your `<body>` tag.
