### ISSUE TITLE
Setting properties does not immediately call observers

### ISSUE THREAD

**Issue by lamby** [fastmail/overture#29]
Hi,

I'm having problems when doing silly things such as:

```js
FastMail.mail.screens.compose.instance
    .beginPropertyChanges()
    .set('subject', 'New subject')
    .endPropertyChanges();
```

The UI itself (ie. the *Subject* field) does not reliably update in the DOM, although I can often "make" it update by clicking somewhere on the page. This is somewhat sub-optimal. I'm guessing that I am just missing some call to an event loop or a manual refresh or (more likely) missing some entire philosophical concept behind the the `ObservableProps` object?

**Comment by chris-morgan** [comment]
Your first guess is correct: Overture has an event loop of its own with multiple queues to handle efficient propagation of values, UI drawing, *&c.* It’s [`O.RunLoop`](http://overturejs.com/docs/foundation/RunLoop.html) (the built docs, incidentally, are out of date, but adequate).

You need to either run [`O.RunLoop.flushAllQueues()`](http://overturejs.com/docs/foundation/RunLoop.html#O_RunLoop_flushAllQueues) after your changes, or wrap it in [`O.RunLoop.invoke()`](http://overturejs.com/docs/foundation/RunLoop.html#O_RunLoop_invoke) like this:

```javascript
O.RunLoop.invoke(() => {
    FastMail.mail.screens.compose.instance.set('subject', 'New subject');
});
```

(BTW, `beginPropertyChanges` and `endPropertyChanges` are generally not needed; they’re only *needed* if you’re updating multiple properties simultaneously that must be indeed changed simultaneously—rare—or if a value may be updated more than once and you don’t want to trigger observers for the intermediate values—also quite uncommon. There are a few more related situations where they’re purely for efficiency, and those are most of the uses in the FastMail UI.)

I was thinking about this very issue of convenience a week or two ago, and whether there was any way of hooking into the dev tools to run `O.RunLoop.flushAllQueues()` at the end of every user invocation; I didn’t find a way of doing it (all I managed was killing the browser by an injudicious `console` Proxy which managed a self-DoS!). If you know or can find any way of doing it, I’d be delighted.

**Comment by lamby** [comment]
Thanks, really really appreciated.

**Comment by lamby** [comment]
@chris-morgan Hi Chris, I'm having new problems here in that whilst I'm calling:

```
FastMail.mail.draft.set('cc', val)
```

... within a `O.RunLoop.invoke` closure, the UI is not being updated.

**Comment by chris-morgan** [comment]
At this point I’m going to say we’re not going to help you with it. Overture is open source (and that’s why I answered your initial query, because it pertained directly to Overture), but the FastMail web interface itself isn’t. If from what you can access you can figure it out, well and good; but we’re not going to provide any direct assistance on it.

**Comment by lamby** [comment]
@chris-morgan Totally understand and appreciate, don't worry. This was not only technically (cheekily?) the wrong venue for such a question, it probably should not be asked anyway. (Saying that, I have some slight aversion to open source projects that have a single main user with essentially a single usage of.. but that's a different, wider topic to be had over a $beverage sometime!)
