### ISSUE TITLE
How to capture 'enter key' press on TextView?

### ISSUE THREAD

**Issue by EliRibble** [fastmail/overture#52]
I'm trying to add search capabilities to the jmap demo client that uses overture. I'd like far a user to be able to type a search term and press enter and have the search performed. I can't figure out from the documentation how to fire a function or capture the enter key press in Overture. Is there a way?

**Comment by neilj** [comment]
You can do this be adding an observer to the TextInputView:

```javascript
new TextInputView({
    [... other config ...]
    submitOnEnter: function (event) {
        if (lookupKey(event) === 'Enter') {
            // Do something
        }
    }.on('keypress'),
}
```
